### ISSUE TITLE
Full simulation

### ISSUE THREAD

**Issue by sanghwapark** [c-dilks/sidis-eic#12]
ATHENA full detector simulation analysis chain is added. 
**AnalysisDD4hep** is an inherited class from **Analysis** which was initially developed to analyze Delphes outputs. Most of the histogram bin settings, input and output file name handling, flags (e.g. Reconstruction method) functions are defined in **Analysis**. 

Some To-dos/wishlist:
- [x] verify the output histograms
- [x] upload example running macros
- [ ] implement PID smearing
- [x] add other hadron truth information 
- [x] fix hard-coded parameters (e.g. energy threshold for the scattered electron, better change to something like ~10% of the beam energy?)
- [ ] asymmetry check
- [ ] clean-up
- [ ] implement track-cluster matching (start with a simple projected distance check?)

**Comment by sanghwapark** [comment]
This doesn't work since the Analysis class is an incomplete type. For now, updated the AnalysisDD4hep to just declare Analysis pointer. Later what we should probably do is to make a base class (say AnalysisBase) for all analysis classes. 

Confirmed the new commit 7e1c59f works again for the Delphes output.

**Comment by c-dilks** [comment]
Closing (for cleaning up old issues); we should eventually go through the `Analysis`-derived classes carefully anyway
